version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: user-manager:v1
    container_name: user-manager
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./xdebug.ini
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 8070:8070